# Generated by Django 3.1.4 on 2021-01-13 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0002_auto_20210109_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='make',
            name='name',
            field=models.CharField(help_text='Enter an item', max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Mínimo dos carácteres por favor')]),
        ),
    ]
